# 문자데이터의 전처리!!!
--- 

문자열 데이터 : 카테고리형(학점, 도시...), 텍스트형(일반적인 문장에 포함된 단어들...)  
  
1. `레이블 인코딩`(순서가 있는 카테고리)  
 예) 학점  
     A->1, B->2, C->3... (숫자가 커질수록 학점이 낮음)  

**주의!!! 레이블 인코딩은 선형회귀와 같은 알고리즘에 적용하면 안됌.**

2. `원핫 인코딩`(순서x)  
 예) 지역  
     서울=1000, 부산=0100, 제주=0010, 강릉=0001  



3. `get_dummies`함수

---

## 1. 레이블 인코딩

In [1]:
from sklearn.preprocessing import LabelEncoder

In [4]:
items = ['tv', '냉장고', '에어컨', '에어컨', '전자레인지']

encorder = LabelEncoder()
encorder.fit(items)
labels = encorder.transform(items) #레이블 인코딩

print(labels)
print(encorder.inverse_transform(labels)) #원 데이터가 다시 출력

[0 1 2 2 3]
['tv' '냉장고' '에어컨' '에어컨' '전자레인지']


## 2. 원핫 인코딩

    * step1 : 원핫 인코딩을 하기 전에 모든 문자열을 숫자로 변환
    * step2 : 숫자로 변환된 데이터(2차원)에 대한 원핫인코딩

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
items = ['tv', '냉장고', '에어컨', '에어컨', '전자레인지']

#step1
encorder = LabelEncoder()
encorder.fit(items)
labels = encorder.transform(items) #레이블 인코딩
print(labels)

#step2
labels = labels.reshape(-1, 1)
ohencorder = OneHotEncoder()
labels = ohencorder.fit_transform(labels)
print(labels.toarray())

[0 1 2 2 3]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 3. `get_dummies`함수 사용

In [14]:
df = pd.DataFrame(['tv', '냉장고', '에어컨', '에어컨', '전자레인지'],
                 columns=['item'])
pd.get_dummies(df)

item_tv  item_냉장고  item_에어컨  item_전자레인지
0        1         0         0           0
1        0         1         0           0
2        0         0         1           0
3        0         0         1           0
4        0         0         0           1