In [1]:
import numpy as np

# numpy의 조건문

In [6]:
#numpy의 if문(조건문) : np.where 함수
xarr = np.array([1,2,3,4,5])
yarr = np.array([2,3,4,5,6])
cond = np.array([True, False, True, True, False]) 

#True일 때는 xarr의 값, False일때는 yarr값 출력

#1. 일반 for, if문을 사용할때
#파이썬 수행 -> 큰 배열이라면 매우 속도가 느림
res = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(res)

#2. np.where을 사용할 때 -> 매우 빠르고 간결하게 수행
res2 = np.where(cond, xarr, yarr) #array형태로 출력 : [1 3 3 4 6]
print(list(res2))

[1, 3, 3, 4, 6]
[1, 3, 3, 4, 6]


In [13]:
arr = np.random.randn(4,4)
print(arr)

#arr에 저장된 값이 0초과면 값을 2로, 0이하 이면 0으로 변경
#np.where함수 사용
print(np.where(arr>0,2,0))
#arr값이 0보다 크면 2로 변경, 그렇지 않으면 arr값 그대로 사용
print(np.where(arr>0, 2, arr))

[[ 1.28240785 -0.3299711   1.33214327  1.47309058]
 [ 2.08419935  0.45079648 -0.32397037 -0.38670438]
 [-0.0268527  -0.23970351  1.42079846  0.2897947 ]
 [-0.79669366 -0.32550937  0.25875585 -0.94355791]]
[[2 0 2 2]
 [2 2 0 0]
 [0 0 2 2]
 [0 0 2 0]]
[[ 2.         -0.3299711   2.          2.        ]
 [ 2.          2.         -0.32397037 -0.38670438]
 [-0.0268527  -0.23970351  2.          2.        ]
 [-0.79669366 -0.32550937  2.         -0.94355791]]


# 수학, 통계 메소드

In [20]:
arr = np.random.randn(5,4)
arr

array([[ 4.35302498e-01, -1.10597814e+00,  1.31335548e-01,
         5.41812989e-01],
       [-1.18288067e-01, -1.36897965e-03, -1.36650288e+00,
        -1.34827484e-01],
       [-7.18365105e-01,  4.80079661e-01, -2.40469839e-01,
         9.16680456e-01],
       [ 8.05694570e-01, -1.60731894e+00,  2.23981318e+00,
        -5.84308484e-01],
       [-7.74461058e-01,  8.80888760e-01,  1.46447045e-01,
         5.17237122e-01]])

In [21]:
#평균
print(arr.mean()) #np.mean(arr)과 같음
print(arr.mean(axis=1)) #행 별로 평균을 구한 값
print(arr.mean(axis=0)) #열 별로 평균을 구한 값

0.022170142388121834
[ 0.00061822 -0.40524685  0.10948129  0.21347008  0.19252797]
[-0.07402343 -0.27073953  0.18212461  0.25131892]


In [22]:
#합계
print(arr.sum())
print(arr.sum(axis=1))
print(arr.sum(axis=0))

0.44340284776243666
[ 0.00247289 -1.62098741  0.43792517  0.85388032  0.77011187]
[-0.37011716 -1.35369764  0.91062305  1.2565946 ]


In [23]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
#cumsum : 누적합
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [30]:
#0~8값으로 초기화 배열 생성, 3*3
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr.cumsum()) #전체값들에 대한 누적합
print(arr.cumsum(axis=0)) #같은 열끼리만 누적합을 진행
print(arr.cumsum(axis=1)) #값은 행끼리만 누적합을 진행

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  3  6 10 15 21 28 36]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [31]:
#cumprod : 누적 곱
print(arr.cumprod()) #전체값들에 대한 누적곱
print(arr.cumprod(axis=0)) #같은 열끼리만 누적곱을 진행
print(arr.cumprod(axis=1)) #값은 행끼리만 누적곱을 진행

[0 0 0 0 0 0 0 0 0]
[[ 0  1  2]
 [ 0  4 10]
 [ 0 28 80]]
[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


# boolean 배열 메소드

In [32]:
arr = np.random.randn(100)
arr

array([ 0.79433355, -3.22981308,  0.45786681, -0.3323804 ,  0.57215055,
        0.29432491, -0.98486749,  0.31143196, -0.19722419,  0.20770387,
       -2.09947751, -0.45115107,  0.69640594,  1.24668057, -0.38650455,
       -0.55709698,  0.65057525,  0.62860648,  0.40837644,  0.00771119,
        0.53938322, -0.0422056 , -1.7901143 ,  0.64792537, -2.26316249,
        0.03666995,  1.09859445, -0.42084818,  1.52708872,  0.75940186,
       -0.67101444,  0.59391022, -1.18119158, -0.87035219,  0.67669163,
        1.02643231,  0.67252752, -0.71080015,  2.85603194,  0.37692344,
       -0.59421263,  0.65500658,  1.66998019,  0.05515551,  1.7124534 ,
        0.00503742, -0.23667961, -2.12399317, -1.06643181,  1.19538745,
        0.05582703,  0.32629691,  0.96889342, -0.28936498,  0.10566338,
       -1.24290155, -1.10281548,  1.74306193,  0.53362724,  0.26104497,
        1.26644826,  0.33170925, -1.0213047 ,  0.18893396, -0.01121671,
       -0.86322014, -1.7351303 ,  1.57443152,  0.15355267, -0.87

In [33]:
arr>0

array([ True, False,  True, False,  True,  True, False,  True, False,
        True, False, False,  True,  True, False, False,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
       False,  True,  True, False,  True, False, False,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False, False, False,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False, False, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True])

In [34]:
#boolean함수도 sum연산이 가능
(arr>0).sum() #False:0, True:1

64

In [35]:
#any, all 함수
bools = np.array([False, False, True, False])
print(bools.any()) #하나 이상의 값이 True -> True
print(bools.all()) #모든 요소값이 True -> True

True
False


# 정렬

In [38]:
#sort함수
arr = np.random.randn(6)
print(arr)
arr.sort()
print(arr)

[-1.91198804  1.55622435  0.90699772  0.89213307 -1.20402707 -0.22459834]
[-1.91198804 -1.20402707 -0.22459834  0.89213307  0.90699772  1.55622435]


In [42]:
arr = np.random.randn(5, 3)
print(arr)

[[-0.5486453  -0.21560643  1.66729781]
 [ 0.87552402 -0.69366513 -0.08179686]
 [ 0.53142222  2.4661755  -2.46016181]
 [-2.43766282  2.04171227  1.16304206]
 [-0.2214488   0.21839191 -0.0812709 ]]


In [45]:
arr.sort()
print(arr)

[[-2.46016181 -2.43766282 -0.69366513]
 [-0.5486453  -0.21560643 -0.08179686]
 [-0.2214488  -0.0812709   0.21839191]
 [ 0.53142222  1.16304206  2.04171227]
 [ 0.87552402  1.66729781  2.4661755 ]]


In [43]:
arr.sort(0) #열 단위로 오름차순 정렬
print(arr)

[[-2.43766282 -0.69366513 -2.46016181]
 [-0.5486453  -0.21560643 -0.08179686]
 [-0.2214488   0.21839191 -0.0812709 ]
 [ 0.53142222  2.04171227  1.16304206]
 [ 0.87552402  2.4661755   1.66729781]]


In [44]:
arr.sort(1) #행 단위로 오름차순 정렬
print(arr)

[[-2.46016181 -2.43766282 -0.69366513]
 [-0.5486453  -0.21560643 -0.08179686]
 [-0.2214488  -0.0812709   0.21839191]
 [ 0.53142222  1.16304206  2.04171227]
 [ 0.87552402  1.66729781  2.4661755 ]]


In [ ]:
#배열.sort() : 원래 배열 자체를 정렬
#np.sort(배열) : 원래의 배열은 그대로 두고 정렬된 결과를 복사본으로 리턴

In [50]:
x = np.array([3,2,5,4,1,9,0])
x.sort()
x

array([0, 1, 2, 3, 4, 5, 9])

In [49]:
x = np.array([3,2,5,4,1,9,0])
np.sort(x)
x

array([3, 2, 5, 4, 1, 9, 0])

In [53]:
x = np.array([3,2,5,4,1,9,0])
np.sort(x)[::-1] #역순으로 정렬
x

array([3, 2, 5, 4, 1, 9, 0])

In [56]:
#x에 저장되어있는 데이터를 오름차순 정렬 했을 경우에
#오름차순 정렬 결과에 대한 원 데이터 인덱스(index)
x = np.array([3,2,5,4,1,9,0])
print(np.argsort(x)) #오름차순 정렬의 인덱스 -> [0이 있는 위치, 1이 있는 위치,...]
print(np.argsort(-x)) #내림차순 정렬의 인덱스
print(x[np.argsort(-x)]) #내림차순 정렬 됌

[6 4 1 0 3 2 5]
[5 2 3 0 1 4 6]
[9 5 4 3 2 1 0]


In [61]:
x = np.array([[2,1,6],
             [0,7,4],
             [5,3,2]])
print(np.sort(x, axis=1)) #행 단위로 정렬, axis는 생략 가능
print(np.sort(x, axis=0)) #열 단위로 정렬

print(np.sort(x, axis=1)[::-1]) #열 축 기준으로 거꾸로 출력
print(np.sort(x, axis=0)[::-1])

[[1 2 6]
 [0 4 7]
 [2 3 5]]
[[0 1 2]
 [2 3 4]
 [5 7 6]]
[[2 3 5]
 [0 4 7]
 [1 2 6]]
[[5 7 6]
 [2 3 4]
 [0 1 2]]


In [ ]:
#튜플 정렬 : sorted(튜플, 키)
#리스트 정렬 : 리스트.sort(), sorted(리스트)
#데이터프레임 정렬 : 데이터프레임.sort_values()

# 집합

In [64]:
names = np.array(['순신', '길동', '꺽정', '길동', '길동'])

In [65]:
#유일한 값만 추출
np.unique(names)

array(['길동', '꺽정', '순신'], dtype='<U2')

In [66]:
#파이썬의 집합함수 : set
set(names)

{'길동', '꺽정', '순신'}

In [68]:
#in1d(배열1, 배열2)
#배열1의 원소가 배열2의 원소를 포함하는지 여부fmf True, False로 출력
np.in1d(names, ['순신', '꺽정'])

array([ True, False,  True, False, False])

# 파일 저장 및 불러오기

In [ ]:
#1개의 배열을 바이너리로 저장 : np.save(), np.load()

In [69]:
x = np.array([0,1,2])
np.save("xsave", x) #x에 저장된 배열을 xsave.npy로 저장

In [70]:
xload = np.load("xsave.npy") #바이너리 파일을 읽음
xload

array([0, 1, 2])

In [ ]:
#여러개의 배열을 바이너리 형태로 압축하여 저장 : np.savez(), np.load()

In [74]:
x = np.array([0,1,2])
y = np.array([3,4,5])

In [76]:
np.savez("xysavez", x=x, y=y) #확장자 : npz

In [79]:
xyload = np.load("xysavez.npz")
print(xyload) #객체로 블러옴
print(xyload['x'])
print(xyload['y'])

[0 1 2]
[3 4 5]


In [80]:
xyload.close() #메모리 해제

In [ ]:
#여러개의 배열을 텍스트 파일로 저장 : np.savetxt
#텍스트파일을 배열로 불러오기 : np.loadtxt

In [82]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [85]:
np.savetxt("xytxt.txt", (x, y), fmt="%.f") #fmt="%.f" : 소수점 이하 제거

In [87]:
xytxtload = np.loadtxt('xytxt.txt')
xytxtload

array([[1., 2., 3.],
       [4., 5., 6.]])

# array 분할

In [ ]:
#numpy배열을 여러개로 분할(split- vertical/horizontal)
#수평축으로 배열 분할 : hsplit, split
#수직축으로 배열 분할 : vsplit, split

In [88]:
x = np.arange(18).reshape(3, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [ ]:
#배열을 수평축(열방향)으로 분할

In [89]:
np.hsplit(x, 3) # x배열을 수평축(열방향)으로 3개의 배열로 분할

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [90]:
np.hsplit(x, (2,4)) #x배열을 수평축(열방향)으로 0:2, 2:4, 4:6

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [92]:
np.split(x, 3, axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [94]:
print(np.split(x, (2,4), axis=1))

x1, x2, x3 = np.split(x, (2,4), axis=1)
print(x1)

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[[ 0  1]
 [ 6  7]
 [12 13]]


In [ ]:
#배열을 수직축(행방향)으로 분할

In [95]:
np.vsplit(x, 3) #행방향으로 3개의 배열 분할

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [96]:
np.vsplit(x, (1,2)) #분할하고자 하는 위치 지정 : x[0:1], x[1:2], x[2:3]

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [97]:
np.split(x, 3, axis=0)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [98]:
np.split(x, (1,2),axis=0)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

# flip 함수

In [99]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
arr[::-1] #행만 거꾸로 출력됌

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [102]:
np.flip(arr, axis=0) #[::-1]과 같은 효과

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [105]:
arr[:, ::-1] #열단위로 거꾸로 출력

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [103]:
np.flip(arr, axis=1) #열단위로 거꾸로 출력

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [106]:
arr[::-1, ::-1] #행과 열 모두 거꾸로 출력

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [104]:
np.flip(arr) #행과 열 모두 거꾸로 출력

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [132]:
a = np.arange(-5, 5)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [111]:
#음수 값은 모두 0으로 대체

#1. 리스트컴프리헨션
res1 = [(0 if x<0 else x) for x in a]
#2. 불린참조(벡터화 연산)
a[a<0] = 0
res2 = a
#3. np.where(벡터화 연산)
res3 = np.where(a<0, 0, a)

print(res1)
print(res2)
print(res3)

[0, 0, 0, 0, 0, 0, 1, 2, 3, 4]
[0 0 0 0 0 0 1 2 3 4]
[0 0 0 0 0 0 1 2 3 4]


In [135]:
#0보다 작으면 0으로 변환, 2보다 크면 2로 변환, 그 사이 값은 그대로 출력

#1. 리스트컴프리헨션
res1 = [(0 if x<0 else (2 if x>2 else x)) for x in a]
# #2. 불린참조(벡터화 연산)
a[a<0] = 0
a[a>2] = 2
res2 = a
#3. np.where(벡터화 연산)
res3 = np.where(a<0, 0, np.where(a>2, 2, a))

print(res1)
print(res2)
print(res3)

[0, 0, 0, 0, 0, 0, 1, 2, 2, 2]
[0 0 0 0 0 0 1 2 2 2]
[0 0 0 0 0 0 1 2 2 2]


In [120]:
#np.clip(배열, 최소값, 최대값)
np.clip(a, 0, 2, out=a)

array([0, 0, 0, 0, 0, 0, 1, 2, 2, 2])

In [121]:
#리스트를 array로 변경
a = [1,2,3]
np.asarray(a) #이미 해당 배열이 있으면 복사하지 않음

array([1, 2, 3])

In [122]:
b = np.array([1,2])
b2 = np.asarray(a)

b is b2

False

In [127]:
b = np.array([1,2])
b2 = np.asarray(b)

np.asarray(b2) is b

True

In [ ]:
#단위행렬(항등행렬): 정방행렬(행과 열의 수가 같음) & 대각성분 '1', 나머지 '0'

In [130]:
print(np.identity(3)) #정방행렬을 만드는 함수1
print(np.eye(3)) #정방행렬을 만드는 함수2

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 행렬  
: 숫자를 사각형으로 나열

종류  
    - 제로행렬 : 요소가 모두 0으로 구성된 행렬  
    - 전치행렬 : nxm -> mxn  
    - 대칭행렬 : 대각 요소를 기준으로 대칭인 정방행렬  
        ex) 1 4 5  
            4 2 2  
            5 2 3  
    - 대각행렬 : 대각요소를 제외한 나머지는 0인 행렬   
        ex) diag(1,2,3)  
            1 0 0  
            0 2 0  
            0 0 3  
            
            diag(1,1,1) => 항등행렬  
            1 0 0  
            0 1 0  
            0 0 1  


* 균등확률 표본복원추출

In [138]:
#모집단 : 0~4
#균등롹률 분포를 따르는 임의의 수 3개 복원추출
#arange(5) 즉 0~4중에서 3개를 랜덤으로 (복원)추출하는 함수 : np.random.choice
np.random.choice(5,3) #np.random.randint(0, 5, 3)

array([1, 4, 1])

In [139]:
np.random.choice(5, 10)

array([4, 1, 2, 1, 4, 3, 3, 3, 4, 4])

* 비균등 확률 표본 복원 추출

In [149]:
p = [0.1, 0.2, 0.2, 0.4, 0.1] #각 원소별 표본으로 뽑힐 확률(가중치)
                              #각 요소의 합은 1이어야 함.
                              #요소는 0~1 사이의 값을 가져야함(확률이므로)

np.random.choice(5, 3) #각 원소가 뽑힐 확률은 균등하게 0.2
np.random.choice(5, 3, p=p)
#모집단의 크기는 p(가중치 배열)의 크기와 같아야 함.
#표본이 추출될 확률은 p의 확률을 따름
# ex) 0이 뽑힐 확률? 0.1
#     1이 뽑힐 확률? 0.2 ...

array([3, 3, 2])

* 비복원 추출

In [157]:
np.random.choice(5,3) #default : 복원 추출
np.random.choice(5,3, replace=False) #replace옵션을 False로 선언해주면 비복원추출

p = [0.1, 0.2, 0.2, 0.4, 0.1]
np.random.choice(5,3, replace=False, p=p)

array([0, 1, 2])

In [160]:
fruits = ['apple', 'banana', 'lemon', 'mango']
p = [0.05, 0.05, 0.7, 0.2]
np.random.choice(fruits, 2, replace=False, p=p)

array(['lemon', 'apple'], dtype='<U6')

* 데이터 수집 -> 전처리 -> 분석 -> 모델링 -> 모델평가 및 개선  
* 모델? 데이터 입력 -> 모델 -> 예측/분류 결과 출력    
  
     ex) 전체 데이터 100개  
        70개 데이터(train) => 모델링 => 30개 데이터(Test) 모델 평가
        30중에서 21개 정답 -> 70% 정확도 모델
    
!!! 서로다른 모델의 성능을 비교하려면 같은 test data로 모델을 평가해야함
    => seed로 동일한 랜덤데이터 생성의 필요성

* 동일한 난수 발생

In [168]:
#np.random.seed() : 동일한 난수를 발생시키는 함수
np.random.seed(1004) #seed를 먼저 주고
np.random.choice(5, 3) #choice를 수행

array([2, 3, 3])

# 데이터 분할(train/ test data)

1. 싸이킷런

In [171]:
from sklearn.model_selection import train_test_split

In [170]:
x = np.arange(20).reshape(10, 2) #중간고사 등수, 기말고사 등수
y = np.arange(10) #최종 시험 등수

In [188]:
xTrain, xTest, yTrain, yTest = train_test_split(x,y,
                 test_size = 0.4, #train_size = 0.6 과 같은 옵션
                 shuffle = True,
                 random_state = 1004) #훈련: 60%, 테스트: 40%
#train_x, train_y : 모델을 만들 때 사용하는 입력/출력 데이터
#test_x, test_y : 모델을 평가할 때 사용되는 입력/출력 데이터

#모델링 후 예측값과 test_y를 비교하여 (오차)차이를 구하는 것을
#mean square error(mse)이라고 하는데 mse값을 통해 성능평가

#xTrain 입력==========> 모델(f) ============> 예측/분류 결과 출력(yTrain)
#xTest입력 => 모델(f) => 예측/분류 결과(yPred) ==> yTest와 비교(성능평가)

# broadcasting   
: 모양이 다른 두 배열 간 연산이 가능하도록 만드는 조건   
     - 1차원 배열이 반드시 포함 되어 있어야 함
     - 계산하는 두 배열이 차원의 짝이 맞아야 함

In [190]:
a = np.array([1,2,3])
b = np.array([1,2])

a+b #ValueError: operands could not be broadcast together with shapes (3,) (2,) 

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [191]:
#1.배열 + 스칼라
np.arange(3)+5 #[0,1,2]배열에서 각 요소에 5(스칼라)를 더한 값을 출력

array([5, 6, 7])

In [193]:
#2. 배열(2차원)+배열(1차원)
#각 행[x,y,z] 마다 [0,1,2]를 더해 [x+0, y+1, z+2]의 값을 출력한다.
#기준 행의 크기와 더하는 배열의 크기가 일치해야 함.
np.arange(11, 20).reshape(3,3) + np.arange(3)

array([[11, 13, 15],
       [14, 16, 18],
       [17, 19, 21]])

In [197]:
#3.배열(nXm) + 배열(mXn)
#각 행의 시작 요소를 기준으로 b의 arange만큼 확장된다.
a = np.arange(3).reshape(3,1) #3행 1열
b = np.arange(3) #1차원배열


a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [204]:
# 같은 차원의 배열의 크기가 같으면 연산 가능
# 1차원크기 : 2 
# 2차원크기 : 2x4
a = np.arange(24).reshape(3, 4, 2)
b = np.arange(8).reshape(4, 2) #2차원 배열
c = np.arange(2) #1차원 배열

print("* a : \n", a)
print("* a+b : \n", a+b)
print("* a+c : \n", a+c)

* a : 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
* a+b : 
 [[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 8 10]
  [12 14]
  [16 18]
  [20 22]]

 [[16 18]
  [20 22]
  [24 26]
  [28 30]]]
* a+c : 
 [[[ 0  2]
  [ 2  4]
  [ 4  6]
  [ 6  8]]

 [[ 8 10]
  [10 12]
  [12 14]
  [14 16]]

 [[16 18]
  [18 20]
  [20 22]
  [22 24]]]
