In [1]:
import pandas as pd 
from math import log
#문장 -> TF(DTM) -> IDF( log(n /(1+df)) ) => TF * IDF(element wise product)

In [9]:
docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
] 

In [15]:

list(set([w for doc in docs for w in doc.split()]))

['사과', '과일이', '저는', '노란', '좋아요', '싶은', '길고', '바나나', '먹고']

In [16]:
docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
] 
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()

In [17]:
vocab

['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']

In [4]:
N = len(docs)

def tf(t, d):
    return d.count(t)

def idf(t):
    df = 0
    for doc in docs:
        df += t in doc
    return log(N/(df + 1))

def tfidf(t, d):
    return tf(t,d)* idf(t)

In [5]:
result = []
for i in range(N): 
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]        
        result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)
tf_

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [6]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))

idf_ = pd.DataFrame(result, index = vocab, columns = ["IDF"])
idf_

IDF
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [7]:
result = []
for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]

        result[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_

과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [19]:
#사이킷런 tfidf
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

In [21]:
vec=CountVectorizer()

In [24]:
print(vec.fit_transform(corpus).toarray()) #코퍼스에서 단어의 빈도수를 추출
vec.vocabulary_

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]


{'you': 7,
 'know': 1,
 'want': 5,
 'your': 8,
 'love': 3,
 'like': 2,
 'what': 6,
 'should': 4,
 'do': 0}

In [25]:
##사이킷런의 tfidf 클래스를 사용하여 tfidf행렬을 구함

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tv=TfidfVectorizer()

In [28]:
tfidfv=tv.fit(corpus)

In [29]:
print(tfidfv.transform(corpus).toarray())

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]


In [30]:
tfidfv.vocabulary_

{'you': 7,
 'know': 1,
 'want': 5,
 'your': 8,
 'love': 3,
 'like': 2,
 'what': 6,
 'should': 4,
 'do': 0}

In [39]:
tv=TfidfVectorizer(ngram_range=(1,2))

In [40]:
tfidfv=tv.fit(corpus)

In [41]:
print(tfidfv.transform(corpus).toarray())

[[0.         0.34142622 0.34142622 0.         0.         0.34142622
  0.         0.         0.34142622 0.34142622 0.         0.
  0.25966344 0.34142622 0.34142622 0.34142622]
 [0.         0.         0.         0.62276601 0.62276601 0.
  0.         0.         0.         0.         0.         0.
  0.4736296  0.         0.         0.        ]
 [0.4472136  0.         0.         0.         0.         0.
  0.4472136  0.4472136  0.         0.         0.4472136  0.4472136
  0.         0.         0.         0.        ]]


In [42]:
tfidfv.vocabulary_

{'you': 12,
 'know': 1,
 'want': 8,
 'your': 14,
 'love': 5,
 'you know': 13,
 'know want': 2,
 'want your': 9,
 'your love': 15,
 'like': 3,
 'like you': 4,
 'what': 10,
 'should': 6,
 'do': 0,
 'what should': 11,
 'should do': 7}

In [ ]:
# -	바나나	사과	저는	좋아요
# 문서1	2	3	0	1
# 문서2	1	2	3	1
# 문서3	2	1	2	2

In [44]:
import numpy as np
doc1=np.array((2,3,0,1))
doc2=np.array((1,2,3,1))
doc3=np.array((2,1,2,2))

In [45]:
docInput=np.array((1,1,0,1))

In [ ]:
#퀴즈1.
#docInput 문서와 가장 가까운 문서를 출력(유클리디안 거리 공식)

In [49]:
def dist(x,y):
    return (np.sqrt(np.sum((x-y)**2)))
    
print(dist(doc1, docInput))
print(dist(doc2, docInput))
print(dist(doc3, docInput))

2.23606797749979
3.1622776601683795
2.449489742783178


In [52]:
#자카드 유사도 알고리즘
#교(집합):두 집합에서 공통으로 가지고 있는 원소 집합
#합(집합):두 집합에서 가지고 있는 원소 집합
#합집합에서 교집합의 비율을 구하자. => 두 문서의 유사도

# J(doc1, doc2)= (doc1 교 doc2) / (doc1 합 doc2)
# 0<=J(doc1, doc2)<=1

#(doc1 합 doc2)=doc1 + doc2 - doc1교doc2


doc1 = "apple banana everyone like likey watch card holder"
doc2 = "apple banana coupon passport love you"

In [55]:
tok1=doc1.split()
tok2=doc2.split()

In [56]:
print(tok1)
print(tok2)

['apple', 'banana', 'everyone', 'like', 'likey', 'watch', 'card', 'holder']
['apple', 'banana', 'coupon', 'passport', 'love', 'you']


In [60]:
#합집합
union=set(tok1).union(set(tok2))
union

{'apple',
 'banana',
 'card',
 'coupon',
 'everyone',
 'holder',
 'like',
 'likey',
 'love',
 'passport',
 'watch',
 'you'}

In [61]:
#교집합
intersection=set(tok1).intersection(set(tok2))
intersection

{'apple', 'banana'}

In [63]:
#자카드 유사도
print("자카드유사도=",len(intersection) / len(union))

자카드유사도= 0.16666666666666666


In [66]:
#퀴즈2.
doc1=np.array((2,3,0,1))
doc2=np.array((1,2,3,1))
doc3=np.array((2,1,2,2))
docInput=np.array((1,1,0,1))

from numpy import dot
from numpy.linalg import norm

def cos_sim(a,b):
    return dot(a,b) / (norm(a)*norm(b))


print(cos_sim(doc1,docInput))
print(cos_sim(doc2,docInput))
print(cos_sim(doc3,docInput))

0.9258200997725515
0.5962847939999439
0.8006407690254358


In [68]:
# def cos_sim(x,y):
#     return sum(x*y)/(sum((x)**2)*sum((y)**2))

# print(cos_sim(doc1,docinput))
# print(cos_sim(doc2,docinput))
# print(cos_sim(doc3,docinput))
# 0.14285714285714285
# 0.08888888888888889
# 0.1282051282051282


# def cos_dist(A):
#     return dot(A, docinput)/(norm(A)*norm(docinput))

# for d in [doc1, doc2, doc3]:
#     print(d, cos_dist(d))
    
#     from sklearn.metrics.pairwise import cosine_similarity

# doc1 = np.array([2,3,0,1])
# doc2 = np.array([1,2,3,1])
# doc3 = np.array([2,1,2,2])

# docInput = np.array([1,1,0,1])

# docs = [doc1,doc2,doc3]

# for doc in docs:
#     cos_sim = cosine_similarity(docInput.reshape(1,-1),doc.reshape(1,-1))
#     print(f'입력 문서와 {doc} 코사인 유사도 : ',cos_sim[0])
    
    
#     def cos_sim(A, B):
#        return dot(A, B)/(norm(A)*norm(B))

# docs = [doc1,doc2,doc3]

# for doc in docs:
#     similarity = cos_sim(docInput, doc)
#     print(f'{doc}와 {docInput}의 코사인유사도:', similarity)

In [ ]:
# 0<= 피어슨 상관계수(x,y)= Covariance(x,y) / (std(x)*std(y)) <=1

# Covariance(x,y)= (Xi-Xu)*(Yi-Yu)

# variance(x)= sum((Xi-Xu)**2) / n
# std(x)=sqrt(variance(x))

In [69]:
#tfidf(줄거리) &cos sim =>  영화추천
import pandas as pd

In [70]:
data=pd.read_csv("movies_metadata.csv", low_memory=False)

In [72]:
data.shape
data.head()

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3  False                                                NaN  16000000   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   

                original_title  \
0                    Toy Story   
1                      Jumanji   
2             Grumpier Old Men   
3            Waiting to Exhale   
4  Father of the Bride Part II   

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2  A family wedding reignites the ancient feud be...  ...   1995-12-22   
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4  Just when George Banks has recovered from his ...  ...   1995-02-10   

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]   
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline  \
0  Released                                                NaN   
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   
3  Released  Friends are the people who let you be yourself...   
4  Released  Just When His World Is Back To Normal... He's ...   

                         title  video vote_average vote_count  
0                    Toy Story  False          7.7     5415.0  
1                      Jumanji  False          6.9     2413.0  
2             Grumpier Old Men  False          6.5       92.0  
3            Waiting to Exhale  False          6.1       34.0  
4  Father of the Bride Part II  False          5.7      173.0  

[5 rows x 24 columns]

In [75]:
data=data.head(20000)

In [76]:
data.shape

(20000, 24)

In [80]:
data['overview']
#전처리

data['overview'].isnull().sum() #''
data['overview']=data['overview'].fillna('')

In [81]:
data['overview'].isnull().sum()

0

In [83]:
#tfidf
tfidfMat=TfidfVectorizer(stop_words='english')
tfidfMat=tfidfMat.fit_transform(data['overview'])
tfidfMat.shape

(20000, 47487)

In [84]:
#(20000, 47487)

In [90]:
print(np.max(tfidfMat[0].toarray()[0]))
tfidfMat[0].toarray().shape

#퀴즈2.
#0.5036643709879097에 해당되는 단어? index번호? 출력

0.5036643709879097


(1, 47487)

In [102]:
idx = tfidfMat[0].toarray().argmax() #최대 tfidf값에 해당되는 단어의 index
vocab = TfidfVectorizer(stop_words = 'english').fit(data['overview']).vocabulary_
[key for key, value in vocab.items() if value == idx][0]

'buzz'

In [108]:
word_index_dict = TfidfVectorizer(stop_words='english').fit(data['overview']).vocabulary_
#word_index_dict
#sorted(word_index_dict.items(),key=lambda x:x[1])
#print(index_word_dict)
idx = np.argmax(tfidfMat[0].toarray()[0])
idx
print(f'해당 단어 : ',index_word_dict[idx][0])

해당 단어 :  buzz


In [109]:
tfidfMat.shape

#tfidf 행렬
#코사인유사도

(20000, 47487)

In [110]:
from sklearn.metrics.pairwise import linear_kernel

In [111]:
cos_sim=linear_kernel(tfidfMat, tfidfMat)

In [112]:
cos_sim.shape

(20000, 20000)

In [116]:
cos_sim[0] #모든 영화와의 코사인 유사도

array([1.        , 0.01575748, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [125]:
#print(data.index)
data['title']

indices=pd.Series(data.index, index=data['title']).drop_duplicates()
indices

title
Toy Story                                                                       0
Jumanji                                                                         1
Grumpier Old Men                                                                2
Waiting to Exhale                                                               3
Father of the Bride Part II                                                     4
                                                                            ...  
Rebellion                                                                   19995
Versailles                                                                  19996
Two in the Wave                                                             19997
Lotte Reiniger: Homage to the Inventor of the Silhouette Film               19998
RKO Production 601: The Making of 'Kong, the Eighth Wonder of the World'    19999
Length: 20000, dtype: int64

In [126]:
# indices['Jumanji']
# Jumanji영화와 코사인 유사도가 가장 높은 20편의 영화제목을 출력(내림차순)
# ex)
# 12000 Kingkong
# 11000 Batman
# ...

1